site_name: FlipperMCE
site_description: "Open Source GameCube Memory Card Emulator"
site_author: "FlipperMCE Team"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flippermce
    - icon: fontawesome/brands/discord
      link: https://discord.gg/a2dnJD3f
nav:
  - Home: index.md
  - Getting Started:
    - FlipperMCE: getting_started.md
    - GCMCE: gcmce.md
  - Features: features.md
  - Menu Guide: navigation.md
  - FAQ: faq.md
  - Splash Generator: splashgen/splashgen.html
  - Releases: https://github.com/flippermce/firmware/releases
theme:
  name: material
  palette:
    scheme: custom

  font:
    text: Roboto
    code: Roboto Mono
  logo: images/FlipperMCE.svg
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - navigation.tracking
extra_css:
  - stylesheets/extra.css
repo_url: "https://github.com/flippermce"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption